
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_meteo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_meteo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Définition des variables globales du projet
vars:
  # Seuil de température maximale (en °C) pour définir un jour comme "chaud".
  # Utilisé dans la macro get_heatwave_events.
  heatwave_temp_threshold: 30
  
  # Nombre minimum de jours consécutifs au-dessus du seuil pour qualifier une vague de chaleur.
  # Valeur par défaut recommandée par les standards climatiques : 3.
  heatwave_min_duration: 3

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_meteo:
    staging:
      +materialized: view
    marts:
      +materialized: table
